# Settings for the app
app:
  # HTML Title
  title: Bike Rack Requests | Mapping Bike Parking Suggestions
  # Header name
  name: Bike Rack Requests
  # Meta description that will show up in Google search results
  meta_description: _(This is a tool to crowdsource bike rack suggestions in University City. It is powered by Shareabouts, a mapping tool to gather public input. Use it to collect suggested locations and comments in a social, engaging process.)

  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: 39.9523524
      lng: -75.1636075
    zoom: 14
    minZoom: 10
    maxZoom: 17
  layers:
    - url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'

    # NOTE: You can add other map layers below!
    #
    # - url: /static/data/philadelphia.geojson
    #   type: json
    #   rules:
    #     - condition: 'true'
    #       style:
    #         color: "#444"
    #         opacity: 0.6
    #         fillOpacity: 0.1
    #         weight: 1

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  bike_rack_request:
    label: _(Bike Rack Request)
    rules:
      - condition: '"{{location_type}}" === "bike_rack_request"'
        # Display landmarks as icons

        icon:
          iconUrl: /static/css/images/markers/dot-0d85e9.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-0d85e9.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]

        # style:
        #   color: '#0d85e9'
        #   radius: 8
        #   weight: 1
        #   opacity: 0.9
        #   fillOpacity: 0.4
        # focus_style:
        #   color: '#0d85e9'
        #   radius: 16
        #   weight: 1
        #   opacity: 0.9
        #   fillOpacity: 0.4


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Request a Bike Rack)
  action_text: _(requested)
  title: _(Snap a photo of the suggested location...)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)
  items:
    - name: location_type
      type: hidden
      attrs:
        - key: value
          value: request_a_bike_rack
    - inputfile_label: _(Add a photo)
      type: file
      name: my_image
      optional: true
      attrs:
        - key: accept
          value: image/*
        - key: required
          value: required
    - prompt: _(Why here?)
      type: textarea
      name: description
      optional: true
    # - prompt: _(Your name)
    #   type: text
    #   name: submitter_name
    #   optional: true
    #   attrs:
    #     - key: size
    #       value: 30
    - prompt: _(Your email)
      help_text: _(We will not share your contact information. We will only use it to follow up with you if we have any questions.)
      type: email
      name: private-email
      optional: true
      attrs:
        - key: size
          value: 30

survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
    start_page: true
